import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

export default function Home() {
  const [dark, setDark] = useState(false);

  return (
    <>
      <Head>
        <title>Blockflow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/blockflow-light.svg" />
      </Head>

      <main
        className={
          dark
            ? `${styles.main} ${styles.dark}`
            : `${styles.main} ${styles.light}`
        }
      >
        {/**Navbar*/}
        <div className={styles.navbar}>
          <div className={styles.hero}>
            <img
              className={styles.logo}
              src={dark ? "/blockflow-dark.svg" : "/blockflow-light.svg"}
              alt="Not Found"
            />
            <p className={styles.title}>blockflow</p>
          </div>

          <div className={styles.items}>
            <p className={styles.item}>DOCS</p>
            <p className={styles.item}>BLOG</p>
            <p className={styles.item}>PRICING</p>
            <p className={styles.item}>CONTACT US</p>
            <img
              className={styles.mode}
              src={dark ? "/sun.svg" : "/moon.svg"}
              onClick={() => {
                setDark(!dark);
                console.log(dark);
              }}
            />
          </div>
        </div>

        {/**Banner*/}
        <div className={styles.banner}>
          {/**Content*/}
          <div className={styles.content}>
            <div className={styles.headText}>
              Elevate Your Dapp Development With Blockflow
            </div>
            <div className={styles.subText}>
              Efficient API Creation for your BlockChain Data Needs.
            </div>
            <button
              className={
                dark ? `${styles["button-dark"]}` : `${styles["button-light"]}`
              }
            >
              Request Demo
            </button>
          </div>

          <img
            className={styles.design}
            src={dark ? "/design-dark.svg" : "/design-light.svg"}
            alt="Not Found"
          />
        </div>

        {/**Light*/}
        <div
          className={
            dark
              ? `${styles.darkSource}`
              : `${styles.darkSource} ${styles.lightSource}`
          }
        >
          <div
            className={
              dark
                ? `${styles.darkEllipse1}`
                : `${styles.darkEllipse1} ${styles.lightEllipse1}`
            }
          >
            <div
              className={
                dark
                  ? `${styles.darkEllipse2}`
                  : `${styles.darkEllipse2} ${styles.lightEllipse2}`
              }
            ></div>
          </div>
        </div>
      </main>
    </>
  );
}
